### PR TITLE
Corrected table format in README.md

### PR DESCRIPTION
**Pull request by ProtyayMnd50**

### CODE REVIEW

**Comment by ProtyayMnd50** [comment]
I have corrected table format as per instructions. Pls review my above pull request.

**Comment by Shubhamlmp** [comment]
@ProtyayMnd50 Please correct Data Type & Conditions section

**Comment by Shubhamlmp** [comment]
@ProtyayMnd50 take a pull from master and resolved conflict.
after that send me MR.

**Comment by ProtyayMnd50** [comment]
> @ProtyayMnd50 Please correct Data Type & Conditions section

You mean the making the spacing uniform  for numbers( for single digit i will be making it adding 0 in front so that will
be solved)

**Pull request merged**
