### PR TITLE
added #96

### PR DESCRIPTION
**Pull request by Aishika3**
this pull request solves issue #96

### CODE REVIEW

**Comment by Aishika3** [comment]
@Shubhamlmp I have added the solution in readme files as well

**Comment by Shubhamlmp** [comment]
@Aishika3 last code is not working can you please check and update and also update your branch

**Comment by Aishika3** [comment]
which one range sum query one?

**Comment by Shubhamlmp** [comment]
> which one range sum query one?

@Aishika3 yes

**Comment by Shubhamlmp** [comment]
@Aishika3 please update your branch then create a PR

**Comment by Aishika3** [comment]
@Shubhamlmp I have updated my branch and pls MR it

**Pull request merged**
