### PR TITLE
Added KMP.cpp

### PR DESCRIPTION
**Pull request by Vikas-hub-cyber**
KMP is string matching algorithm . Detailed analysis with comments

### CODE REVIEW

**Comment by Shubhamlmp** [comment]
@Vikas-hub-cyber problem number

**Comment by Vikas-hub-cyber** [comment]
@Shubhamlmp  This is algorithm for string matching. Please review it and accept it.

**Comment by Vikas-hub-cyber** [comment]
@Shubhamlmp  I added a new problem_solution here with code 
Problem no.-> 22 
Problem Link->https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/V
https://github.com/Shubhamlmp/Programming-Practice/pull/110/commits/83d34cfa736b4833f3cdda9bb56184a4c9c75272

**Comment by Vikas-hub-cyber** [comment]
@Shubhamlmp  Please review it .

**Pull request merged**
