### PR TITLE
Add : Butterfly pattern program

### PR DESCRIPTION
**Pull request by Kunal-Khairnar-05**

### CODE REVIEW

**Comment by Shubhamlmp** [comment]
@Kunal-Khairnar-05  also add link for the solution in readme file in same MR

**Comment by Kunal-Khairnar-05** [comment]
Done : added solution in Readme.md

**Comment by Shubhamlmp** [comment]
@Kunal-Khairnar-05  please remove extra .exe file and send MR again.
also take pull from masters

**Comment by Kunal-Khairnar-05** [comment]
Is that okay?

**Pull request merged**
