### PR TITLE
Search-Insert-Position.cpp

### PR DESCRIPTION
**Pull request by sampaddey**
Please merge my pull request for hacktoberfest 2022.

### CODE REVIEW

**Comment by Shubhamlmp** [comment]
@sampaddey add path for the solution in readme file and after that send MR again.

**Comment by Shubhamlmp** [comment]
@sampaddey update your master branch and then your branch.
after that resolve merge conflicts and share MR again.

**Comment by Shubhamlmp** [comment]
@please resolve conflict

**Comment by sampaddey** [comment]
Please look into my PR, if there are any further problems.

**Pull request merged**
