### PR TITLE
Basic Data Types

### PR DESCRIPTION
**Pull request by ajju-1209**
Added c++ code for Basic Data Types

### CODE REVIEW

**Comment by Shubhamlmp** [comment]
@ajju-1209 pr is good for me just add exact file name as problem name

**Comment by ajju-1209** [comment]
where do you me add file name?

**Comment by ajju-1209** [comment]
Bro you have'nt added the hacktober fest label

**Comment by Shubhamlmp** [comment]
> where do you me add file name?

Like when running file so you create something like abc.cpp like this

**Comment by Shubhamlmp** [comment]
> Bro you have'nt added the hacktober fest label

In each and every issue i added hacktoberfest label

**Pull request merged**
